/*  Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"

Output:
e */

class Solution {
public:
    char findTheDifference(string s, string t) {
        int n=s.size();
        vector<int> count(26,0);
        for(char ch:s){
            count[ch-'a']++;
        }
        for(char ch:t){
            if(count[ch-'a']==0)
                return ch;
            count[ch-'a']--;
        }
        return 'a';
    }
};